@BI.Decorators.model()
export class DemoPaneModel extends BI.Decorators.Model {
  static xtype = "demo-pane-model";

  // mock data
  state = {
    widgets: {
      "4be502ad4f9ac084": {
        explainConf: {
          fieldCombinationList: [[]],
          useDefault: false,
        },
        type: 1,
        name: '${"alt":"__widget_name_id__"}',
        timeStamp: 1764226856616,
        tableName: ["0cd86b6b5aa54b1db82ae466819b5ae6"],
        fields: [],
        widgetMeasures: [
          {
            id: "0cd86b6b5aa54b1db82ae466819b5ae6_Category",
            group: {
              group_11: {
                repeatCal: true,
                useDataBar: false,
                showMissingTime: false,
                depGroup: true,
              },
              group_22: {
                repeatCal: true,
                useDataBar: false,
                showMissingTime: false,
                depGroup: true,
              },
              group_23: {
                repeatCal: true,
                useDataBar: false,
                showMissingTime: false,
                depGroup: true,
              },
            },
          },
          {
            id: "0cd86b6b5aa54b1db82ae466819b5ae6_middle class",
            group: {
              group_11: {
                repeatCal: true,
                useDataBar: false,
                showMissingTime: false,
                depGroup: true,
              },
              group_22: {
                repeatCal: true,
                useDataBar: false,
                showMissingTime: false,
                depGroup: true,
              },
              group_23: {
                repeatCal: true,
                useDataBar: false,
                showMissingTime: false,
                depGroup: true,
              },
            },
          },
        ],
        injection: null,
        widgetModel: {
          type: 0,
        },
        settings: {
          nameStyleType: 1,
          titleHeight: 25,
          emptyDisplayValue: "default",
          titleBackground: {
            type: "color",
            color: "",
            imageId: "",
          },
          widgetBackground: {
            type: "color",
            color: "",
            imageId: "",
            borderSize: -1,
            borderRadius: -1,
            borderColor: "",
          },
          gisBackground: {
            normal: false,
            layer: "normal",
            show: true,
            enableWheelTitle: "Enable Zoom by Wheel",
            disableWheelTitle: "Disable Zoom by Wheel",
            mergeNineLineDashed: false,
          },
          chartAttr: {},
          chartStyle: {
            legend: {
              enabled: true,
              fontStyle: {
                auto: true,
                fontFamily:
                  'Avenir, Segoe UI, PingFangSC-Regular, "Microsoft YaHei"',
                fontSize: 12,
                fontBold: false,
                italic: false,
                fontColor: "",
                type: 0,
                bold: false,
                fontAlign: 0,
              },
              borderColor: "transparent",
              position: "bottom-center",
              titleEnabled: true,
              validMapping: null,
            },
            axis: {
              enabled: true,
              type: "solid",
              color: "",
              width: 1,
            },
            hGrid: {
              enabled: true,
              type: "dashed",
              color: "",
              width: 1,
            },
            vGrid: {
              enabled: true,
              type: "dashed",
              color: "",
              width: 1,
            },
            section: {
              enabled: true,
              type: "solid",
              color: "",
              width: 1,
            },
            background: {
              enabled: true,
            },
            adaptive: {
              enabled: true,
              type: "standard",
            },
          },
          tableAttr: {
            color: {
              all: {
                color: "",
                backgroundColor: "",
                dims: [],
                conditions: [],
                affectSumRow: false,
                applyToLine: false,
              },
            },
            shape: {
              all: {
                shape: -1,
                dims: [],
                conditionsList: [],
                color: "",
                affectSumRow: false,
              },
            },
            filterValue: {},
            equalDivideColumn: false,
          },
          tableStyle: {
            form: 1,
            style: 0,
            themeColor: null,
            metric: {
              show: true,
              position: 3,
              type: 2,
            },
            freezeDim: true,
            freezeNumbers: 1,
            showSequence: false,
            showRowInfo: true,
            headerTextWrapper: false,
            textWrapper: false,
            expandRowHeader: false,
            expandColHeader: false,
            showRowSum: true,
            showColSum: true,
            showChildRowSum: false,
            showChildColSum: false,
            rowPosition: "bottom",
            colPosition: "right",
            sumRowText: "",
            headerRowHeight: 32,
            rowHeight: 32,
            detailRowCounts: 100,
            rowCounts: 20,
            colCounts: 7,
            totalRows: 1000,
            font: {
              type: 1,
              header: {
                fontFamily: null,
                fontSize: null,
                bold: null,
                italic: null,
                underline: null,
                fontAlign: null,
                fontColor: null,
              },
              body: {
                fontFamily: null,
                fontSize: null,
                bold: null,
                italic: null,
                underline: null,
                dimFontAlign: null,
                tarFontAlign: null,
                fontColor: null,
              },
            },
            sumRowInGroupText: "",
            sumColText: "",
            sumColInGroupText: "",
            rowSum: {
              font: {
                fontAlign: null,
                bold: true,
                italic: null,
                underline: null,
                fontColor: null,
                fontFamily: null,
                fontSize: null,
              },
              fontType: 1,
              background: "",
            },
            colSum: {
              font: {
                fontAlign: null,
                bold: true,
                italic: null,
                underline: null,
                fontColor: null,
                fontFamily: null,
                fontSize: null,
              },
              fontType: 1,
              background: "",
            },
            rowSumInGroup: {
              font: {
                fontAlign: null,
                bold: true,
                italic: null,
                underline: null,
                fontColor: null,
                fontFamily: null,
                fontSize: null,
              },
              fontType: 1,
              background: "",
            },
            colSumInGroup: {
              font: {
                fontAlign: null,
                bold: true,
                italic: null,
                underline: null,
                fontColor: null,
                fontFamily: null,
                fontSize: null,
              },
              fontType: 1,
              background: "",
            },
            showRowHeaderIcon: true,
            showColHeaderIcon: true,
            showTitle: false,
            transmitLinkages: false,
          },
          transmitLinkages: true,
          widgetDarkPreview: false,
          chartInitState: {
            mapZoom: -1,
            mapCenter: {
              lat: -1,
              lng: -1,
            },
            mapZoomDisabled: false,
          },
          innerGap: {
            topGap: -2,
            bottomGap: -2,
            leftGap: -2,
            rightGap: -2,
          },
        },
        view: {
          10000: ["8fffd13a13e6b256", "b6834d1c0e8ffe4a"],
          20000: [],
          30000: [],
        },
        viewAttr: {
          10000: {
            type: 1,
            left: {
              reversed: false,
              log: false,
              sharedDomain: true,
            },
            right: {
              reversed: false,
              log: false,
              sharedDomain: true,
            },
            size: 0,
          },
          20000: {
            type: 1,
            size: 0,
          },
          30000: {
            type: 1,
            left: {
              reversed: false,
              log: false,
              sharedDomain: true,
            },
            right: {
              reversed: false,
              log: false,
              sharedDomain: true,
            },
            size: 0,
          },
        },
        dimensions: {
          "8fffd13a13e6b256": {
            name: "Category",
            type: 1,
            notShowNull: false,
            id: "8fffd13a13e6b256",
            fieldId: "0cd86b6b5aa54b1db82ae466819b5ae6_Category",
            toCountType: 0,
            group: {
              type: 11,
            },
            calculation: {
              type: 0,
              value: 0,
            },
            filter: null,
            settings: {
              trendLine: [],
              cordon: [],
              categoryAxis: {
                title: {
                  displayed: false,
                  modified: false,
                },
              },
              valueAxis: {
                reversed: false,
                log: false,
                sharedDomain: true,
              },
              annotate: [],
              size: 0,
              stack: false,
              formatStyle: 1,
              formatDecimal: -1,
              numLevel: 1,
              showType: 0,
              formatPattern: -1,
              numSeparators: true,
              showHeaderPercent: false,
              showSum: false,
              tableShape: {
                shape: -1,
                color: "",
                filters: [],
              },
              tableColor: {
                color: "",
                backgroundColor: "",
                filters: [],
                applyToLine: false,
              },
              unit: "",
              dateFormat: {},
              flash: [],
              imageData: [],
            },
            showMissingTime: false,
            metric: 0,
            counterDep: "TOTAL_ROWS",
            repeatCal: true,
            formatStyle: 0,
            formatDecimal: 0,
            numLevel: 0,
            numSeparators: false,
            used: true,
            drillDimensions: {},
          },
          b6834d1c0e8ffe4a: {
            name: "middle class",
            type: 1,
            notShowNull: false,
            id: "b6834d1c0e8ffe4a",
            fieldId: "0cd86b6b5aa54b1db82ae466819b5ae6_middle class",
            toCountType: 0,
            group: {
              type: 11,
            },
            calculation: {
              type: 0,
              value: 0,
            },
            filter: null,
            settings: {
              trendLine: [],
              cordon: [],
              categoryAxis: {
                title: {
                  displayed: false,
                  modified: false,
                },
              },
              valueAxis: {
                reversed: false,
                log: false,
                sharedDomain: true,
              },
              annotate: [],
              size: 0,
              stack: false,
              formatStyle: 1,
              formatDecimal: -1,
              numLevel: 1,
              showType: 0,
              formatPattern: -1,
              numSeparators: true,
              showHeaderPercent: false,
              showSum: false,
              tableShape: {
                shape: -1,
                color: "",
                filters: [],
              },
              tableColor: {
                color: "",
                backgroundColor: "",
                filters: [],
                applyToLine: false,
              },
              unit: "",
              dateFormat: {},
              flash: [],
              imageData: [],
            },
            showMissingTime: false,
            metric: 0,
            counterDep: "TOTAL_ROWS",
            repeatCal: true,
            formatStyle: 0,
            formatDecimal: 0,
            numLevel: 0,
            numSeparators: false,
            used: true,
            drillDimensions: {},
          },
        },
        allData: true,
        drillOrder: [],
        resultFilter: [],
        dimensionGroups: {
          "0cd86b6b5aa54b1db82ae466819b5ae6_Category_11": {
            group: "0cd86b6b5aa54b1db82ae466819b5ae6_Category_11",
            dimensionIds: ["8fffd13a13e6b256"],
          },
          "0cd86b6b5aa54b1db82ae466819b5ae6_middle class_11": {
            group: "0cd86b6b5aa54b1db82ae466819b5ae6_middle class_11",
            dimensionIds: ["b6834d1c0e8ffe4a"],
          },
        },
        legendFilter: null,
        columnSize: [],
        regionColumnSize: [],
        equallyDivideColumn: false,
        quickSettingClosed: false,
        uploadedImages: [],
        widgetParameters: [],
        manualPreview: false,
        queryInfo: {
          mobile: false,
          bounds: {
            height: 0,
            left: 0,
            top: 0,
            width: 0,
          },
          previewCalLimit: 1,
        },
        preview: false,
        page: 0,
        yPage: 0,
        xPage: 0,
        realData: false,
        templateChartColorChange: false,
        detailSetting: false,
        tableWidth: 0,
        seqColWidth: 0,
        selectTable: "",
        allowOverlap: false,
        openJump: true,
        bounds: {
          height: 460.056,
          left: 230.417,
          top: 0,
          width: 384.028,
        },
        mobile: false,
        wId: "4be502ad4f9ac084",
        measures: [],
        fieldsConfig: {},
        showTitle: true,
        addTime: 1764226924322,
        realWidgetId: "460dc5a66b5d446895d2722c780dea04",
        jump: [],
        showQuickSetting: false,
        sourceName: "Component",
        linkage: {},
      },
      "7c3a422caeedf0f6": {
        timeStamp: 1764594033132,
        name: "Text Drop-Down",
        queryInfo: {
          mobile: false,
          bounds: {
            height: 70.778,
            left: 263.333,
            top: 460.056,
            width: 263.333,
          },
          previewCalLimit: 1,
        },
        manualPreview: false,
        preview: false,
        view: {
          10000: ["d4ab463490f67cbb"],
          20000: [],
          30000: [],
        },
        dimensions: {
          d4ab463490f67cbb: {
            name: "Category",
            type: 1,
            notShowNull: false,
            id: "d4ab463490f67cbb",
            fieldId: "0cd86b6b5aa54b1db82ae466819b5ae6_Category",
            toCountType: 0,
            sort: {
              targetFieldId: "0cd86b6b5aa54b1db82ae466819b5ae6_Category",
              type: 6,
            },
            filter: null,
            showMissingTime: false,
            metric: 0,
            repeatCal: true,
            formatStyle: 0,
            formatDecimal: 0,
            numLevel: 0,
            numSeparators: false,
            used: true,
          },
        },
        page: 0,
        yPage: 0,
        xPage: 0,
        realData: false,
        allData: false,
        templateChartColorChange: false,
        detailSetting: false,
        settings: {
          transmitLinkages: false,
          titleHeight: 0,
          nameStyleType: 0,
          innerGap: {
            topGap: -1,
            bottomGap: -1,
            leftGap: -1,
            rightGap: -1,
          },
          widgetDarkPreview: false,
        },
        tableWidth: 0,
        seqColWidth: 0,
        equallyDivideColumn: false,
        quickSettingClosed: false,
        controlRange: {
          type: 1,
          value: [],
        },
        useCustom: false,
        useOptionRange: false,
        useWidgetParameter: false,
        hideSelectAll: false,
        originDefaultValue: 0,
        sizePercent: 0,
        useCustomSize: false,
        singleSelect: 1,
        sort: "asc",
        allowPassDefault: false,
        parameterFields: [],
        customValue: [],
        type: 32,
        allowOverlap: false,
        openJump: true,
        bounds: {
          height: 70.778,
          left: 263.333,
          top: 460.056,
          width: 263.333,
        },
        mobile: false,
        wId: "7c3a422caeedf0f6",
        tableName: ["0cd86b6b5aa54b1db82ae466819b5ae6"],
        measures: [],
        useParameter: false,
        parameterValue: [],
        bindParameters: [],
        showTitle: true,
        addTime: 1764576250645,
        linkage: {},
      },
    },
    widget: {
      timeStamp: 1764594033132,
      name: "Text Drop-Down",
      queryInfo: {
        mobile: false,
        bounds: {
          height: 70.778,
          left: 263.333,
          top: 460.056,
          width: 263.333,
        },
        previewCalLimit: 1,
      },
      manualPreview: false,
      preview: false,
      view: {
        10000: ["d4ab463490f67cbb"],
        20000: [],
        30000: [],
      },
      dimensions: {
        d4ab463490f67cbb: {
          name: "Category",
          type: 1,
          notShowNull: false,
          id: "d4ab463490f67cbb",
          fieldId: "0cd86b6b5aa54b1db82ae466819b5ae6_Category",
          toCountType: 0,
          sort: {
            targetFieldId: "0cd86b6b5aa54b1db82ae466819b5ae6_Category",
            type: 6,
          },
          filter: null,
          showMissingTime: false,
          metric: 0,
          repeatCal: true,
          formatStyle: 0,
          formatDecimal: 0,
          numLevel: 0,
          numSeparators: false,
          used: true,
        },
      },
      page: 0,
      yPage: 0,
      xPage: 0,
      realData: false,
      allData: false,
      templateChartColorChange: false,
      detailSetting: false,
      settings: {
        transmitLinkages: false,
        titleHeight: 0,
        nameStyleType: 0,
        innerGap: {
          topGap: -1,
          bottomGap: -1,
          leftGap: -1,
          rightGap: -1,
        },
        widgetDarkPreview: false,
      },
      tableWidth: 0,
      seqColWidth: 0,
      equallyDivideColumn: false,
      quickSettingClosed: false,
      controlRange: {
        type: 1,
        value: [],
      },
      useCustom: false,
      useOptionRange: false,
      useWidgetParameter: false,
      hideSelectAll: false,
      originDefaultValue: 0,
      sizePercent: 0,
      useCustomSize: false,
      singleSelect: 1,
      sort: "asc",
      allowPassDefault: false,
      parameterFields: [],
      customValue: [],
      type: 32,
      allowOverlap: false,
      openJump: true,
      bounds: {
        height: 70.778,
        left: 263.333,
        top: 460.056,
        width: 263.333,
      },
      mobile: false,
      wId: "7c3a422caeedf0f6",
      tableName: ["0cd86b6b5aa54b1db82ae466819b5ae6"],
      measures: [],
      useParameter: false,
      parameterValue: [],
      bindParameters: [],
      showTitle: true,
      addTime: 1764576250645,
      linkage: {},
    },
    templateStyle: {
      predictionStyles: [],
      style: {
        id: null,
        theme: null,
        name: null,
        initTime: 0,
        widgetGap: -1,
        templateBackground: {
          type: null,
          color: null,
          imageId: null,
        },
        widgetBackground: {
          type: null,
          color: null,
          imageId: null,
          borderRadius: -1,
          borderSize: -1,
          borderColor: null,
        },
        imageWidgetBackground: {
          type: null,
          color: null,
          imageId: null,
          borderRadius: -1,
          borderSize: -1,
          borderColor: null,
        },
        titleBackground: {
          type: null,
          color: null,
          imageId: null,
        },
        titleFont: {
          type: 0,
          fontFamily: null,
          fontSize: 0,
          bold: false,
          italic: false,
          underline: false,
          fontColor: null,
          fontAlign: 0,
        },
        chart: {
          gradient: null,
          chartColor: null,
          font: {
            type: 0,
            fontFamily: null,
            fontSize: 0,
            bold: false,
            italic: false,
            underline: false,
            fontColor: null,
          },
          customChartColor: false,
        },
        table: {
          tableStyle: 0,
          themeColor: null,
          scrollbarType: 1,
          font: {
            type: 0,
            header: {
              fontFamily: null,
              fontSize: 0,
              bold: false,
              italic: false,
              underline: false,
              fontColor: null,
              fontAlign: 0,
            },
            body: {
              fontFamily: null,
              fontSize: 0,
              bold: false,
              italic: false,
              underline: false,
              fontColor: null,
              dimFontAlign: 0,
              tarFontAlign: 0,
            },
          },
        },
        controlTheme: null,
        controlWidget: {
          titleFont: {
            type: 0,
            fontFamily: null,
            fontSize: 0,
            bold: false,
            italic: false,
            underline: false,
            fontColor: null,
            fontAlign: 0,
          },
          titleBackground: {
            type: null,
            color: null,
            imageId: null,
          },
          widgetBackground: {
            type: null,
            color: null,
            imageId: null,
            borderRadius: -1,
            borderSize: -1,
            borderColor: null,
          },
        },
        styleThemeColor: null,
        currentStyleTab: 0,
        tabWidget: null,
        hoverShadow: true,
      },
    },
    freeWidgetIds: [],
    templateHelper: BI.TemplateHelperService.getMap().entries().toArray()[0][1],
  };

  childContext = [
    "widgets",
    "widget",
    "templateStyle",
    "freeWidgetIds",
    "templateHelper",
  ];
}

@BI.Decorators.shortcut()
@BI.Decorators.store(DemoPaneModel)
export class DemoPane extends BI.Pane {
  static xtype = "demo-pane";

  mounted() {
    console.log("mounted");
  }

  render() {
    return {
      type: "bi.design.widget.template",
    };
  }
}

window.demoPane = BI.createWidget({
    type: DemoPane.xtype,
});

// demoPane is a component reference. Through demoPane.element, you can get the jQuery object of the component, and through demoPane._children, you can get the map of child elements.
// Traverse demoPane and its child elements to integrate them into a jQuery object, taking into account that child elements may contain their own child elements.
window.demoDom = function() {
  const dom = $(demoPane.element);
  function appendChildElements(elementMap, parentDom) {
    Object.values(elementMap).forEach((child) => {
      const childDom = $(child.element);
      parentDom.append(childDom);
      if (child._children) {
        appendChildElements(child._children, childDom);
      }
    });
  }
  appendChildElements(demoPane._children, dom);
  return dom;
};
const realDom = demoDom();
realDom.css('z-index', 1000);
realDom.css('position', 'relative');
realDom.css('width', '500px');
realDom.css('height', '100px');
document.body.appendChild(realDom.get(0));
console.log(realDom);